### ISSUE TITLE
GitHub Pages Option for Connecting the site using wrong image and causing errors

### ISSUE THREAD

**Issue by burntcustard** [tinacms/tina.io#1487]
The [Option: GitHub Pages section](https://tina.io/docs/tina-cloud/connecting-site/#option-github-pages) of the Going To Production > Connecting the Site page has a few major issues:

1. It's showing two identical screenshots, each with `tinacms build &&` highlighted. I assume the second one is supposed to be a different image, showing the `clientID` and `token` environment variables having been added to `nextjs.yml`.
2. The alt text of "GitHub Actions" does not appropriately describe the text content of the image(s) in that section. I think ideally both screenshots would be in text rather than screenshot-form, so that those using screen readers could access the content which isn't really shown anywhere else on the page. If that's not easy to do, then for these I think it makes sense to include the entire (very long) text contents within the alt text, or within a visually-hidden separate element.
3. The modified line in the screenshotted `nextjs.yml` throws a `/home/runner/work/_temp/c1208fd8-133c-4b93-9224-89533d34f4b9.sh: line 1: next: command not found` error, as `${{ steps.detect-package-manager.outputs.runner }}` is needed (at least for me with npm), for each of the individual `tinacms build` and `next build` commands. I worked around this myself with:
   ```
   jobs:
     # Build job
     build:
       runs-on: ubuntu-latest
       steps:
         [...]
         - name: tinacms build
           run: ${{ steps.detect-package-manager.outputs.runner }} tinacms build
         - name: Build with Next.js
           run: ${{ steps.detect-package-manager.outputs.runner }} next build
   ```
4. Not sure if this one is specific to my own site, but I also had to rename `out/home.html` to `out/index.html` to fix the homepage 404'ing:
   ```
         - name: Rename home to index so the homepage works
           run: mv out/home.html out/index.html
   ```

I'd be happy to help with a PR for some or all of these, but I don't have similar-looking images for the screenshot(s), and I'd want to confirm first if I'm doing something wonky that's causing e.g. needing the `mv` of `home.html`?
